<?php
require_once 'restfulresource_class.inc';

function restfulresource_init() {
  $r = new RestfulResource('restfulresources', 'restfulresource');
  $r->removeDefaultActions();
  $r->get->addAction('summary', 'restfulresource_summary');
}

function restfulresource_menu() {
  return RestfulResource::generateMenu();
}

function restfulresource_summary() {
  return 'lookin good!';
}

function restfulresource_router( $resource ) {
  $args = func_get_args();
  array_shift($args);
  return RestfulResource::route( $resource, $args );
}
