<?php
require_once 'restfulresource_class.inc';

function restfulresource_init() {
  $resource = restfulresource_create( 'restfulresources' );
  
  $resource->removeDefaultActions();
  $resource->get->addAction('routes', 'routes');
  $resource->get->addAction('restfulresources', 'resources');
}

function restfulresource_menu() {
  return RestfulResource::generateMenu();
}

function restfulresource_create( $resource, $prefix = '', $module = null ) {
  if (empty($module)) {
    $caller = debug_backtrace(false);
    // it's going to be the second one, the first caller is this function.
    $module = trim($caller[1]['function'], "_init");
  }
  return new RestfulResource( $resource, $prefix, $module );
}

function restfulresource_router( $resource ) {
  $args = func_get_args();
  array_shift($args);
  return RestfulResource::route( $resource, $args, file_get_contents('php://input') );
}

/**
 * APIS
 */
function restfulresource_rr_routes() {
  return RestfulResource::generateMenu();
}

function restfulresource_rr_resources( $data, $id = null ) {
  if ($id) {
    return RestfulResource::$resources[$id];
  }
  else {
    return RestfulResource::$resources;
  }
}

